"""empty message

Revision ID: 2b7acf8dcc1b
Revises: a6bf512ea82f
Create Date: 2020-10-22 11:58:11.490756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7acf8dcc1b'
down_revision = 'a6bf512ea82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    # ### end Alembic commands ###
