"""empty message

Revision ID: 572128383889
Revises: ca3fd8ba8886
Create Date: 2020-10-22 12:25:02.495861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572128383889'
down_revision = 'ca3fd8ba8886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('method1', 'outputimage',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('method1', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    op.alter_column('method1', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('method1', 'outputimage',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
