"""empty message

Revision ID: 594a273f336b
Revises: 59c33ca3fc42
Create Date: 2020-10-22 12:32:26.164281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594a273f336b'
down_revision = '59c33ca3fc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('method1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('outputimage', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    op.drop_table('method1')
    # ### end Alembic commands ###
