"""empty message

Revision ID: beec4cba95b2
Revises: 684dac55630e
Create Date: 2020-10-22 10:37:52.055880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beec4cba95b2'
down_revision = '684dac55630e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    # ### end Alembic commands ###
