"""empty message

Revision ID: ca3fd8ba8886
Revises: 2b7acf8dcc1b
Create Date: 2020-10-22 12:12:11.238897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3fd8ba8886'
down_revision = '2b7acf8dcc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    # ### end Alembic commands ###
