"""empty message

Revision ID: d16400eae0fc
Revises: ec11c90e91a8
Create Date: 2020-10-21 07:50:42.591853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16400eae0fc'
down_revision = 'ec11c90e91a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methods', sa.Column('folder', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'methods', ['body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    op.drop_column('methods', 'folder')
    # ### end Alembic commands ###
